sensive_routes = {
    "/admin":5,
    "/admin/login":5,
    "/dashboard":4,
    "/panel":4,
    "/panel/login":4,
    "panel/dashboard":4,
    "/control":4,
    "/control/dashboard":4,
    "/management":5,
    "/management/dashboard":5,
    "/manager":5,
    "/manager/dashboard":5,
    "/api/dashboard":3,
    "/api/dashboard/dashboard":3,
    "/api/admin":5,
    "/api/admin/dashboard":5,
    "/developer":4,
    "/developer/dashboard":4,
    "/api/data":5,
    "/dev":4,
    "/dev/dashboard":4,
    "/tmp/dashboard":5,
    "/tmp/dashboard/dashboard":5,
    "/tmp":5,
    "/private":5,
    "/private/dashboard":5,
    "/backup":5,
    "/backup/dashboard":5,
    "/console":5,
    "/console/dashboard":5,
    "/settings":5,
    "/settings/dashboard":5,
    "/debug":5,
    "/debug/dashboard":5,
    "/log":5,
    "/env":5,
    "/env/dashboard":5,

}
score_weights = {
    "sensitive_routes": 0.6
}